module.exports = {
    content: [
        "/index.html",
        "/public/pages/cardium.html",
        "/public/pages/ecometer.html",
        "/public/pages/ecometer_desktop.html",
        "/public/pages/graphs.html",
        "/public/pages/ice_adventure.html",
        "/public/pages/json_parser.html",
        "/public/pages/melodica.html",
        "/public/pages/minesweeper.html",
        "/public/pages/portfolio.html",
        "/public/pages/rhythm_ninja.html",
        "/public/pages/tower.html",
        "/public/pages/weave.html",
        "/src/styles.css",
        "/src/components/projectCard.js",
        "/src/components/timelineRow.js",
        "/src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ["Inter", "sans-serif"],
            },
        },
    },
    safelist: [
        'bg-java',
        'bg-javascript',
        'bg-c',
        'bg-cpp',
        'bg-csharp',
        'bg-dart',
        'bg-tailwind',
        'bg-godot',
        'bg-unity',
        {pattern: /bg-.+/},
    ],
    plugins: [],
};