export const experiences = [
  {
    name: "Junior Software Engineer",
    company: "Education First",
    companyUrl: "https://www.ef.com/",
    logo: "/images/experience/ef.png",
    time: "July 2025 - August 2025",
    location: "Budapest, Hungary",
    footer: "",
    description: "Full-stack development in the High School Exchange Year team using ASP.NET Core (C#, Razor, MVC), Entity Framework, with JavaScript (Knockout.js, jQuery, AJAX), MSSQL and MongoDB. Working with Azure, Azure DevOps for CI/CD, and the Atlassian suite. Got exposed to Salesforce too.",
  },
  {
    name: "Flutter Developer",
    company: "Ecometer Kft.",
    companyUrl: "https://ecometer.hu/",
    logo: "/images/experience/ecometer.png",
    time: "May 2024 - Present (part-time)",
    location: "Budapest, Hungary (remote)",
    footer: "",
    description: "Cross-platform mobile and desktop app development in Flutter (Dart, BLoC) using GitHub. Communication with the server through RESTful APIs and with taximeter units via Bluetooth. Full responsibility for frontend tasks. Designed both apps in Figma.",
  },
  {
    name: "R&D Intern",
    company: "Ericsson AB",
    companyUrl: "https://www.ericsson.com/",
    logo: "/images/experience/ericsson.png",
    time: "Jun 2023 - Dec 2023",
    location: "Gothenburg, Sweden",
    footer: "",
    description: "Unit-test generator plugin development for Clang in modern C++ using GitLab, achieving up to 80% code coverage. Scripting in Bash. Weekly standups, and a project presentation at the end of the internship.",
  },
  {
    name: "Mobile Software Developer",
    company: "Arteries Studio Kft.",
    companyUrl: "https://arteries.hu/en/",
    logo: "/images/experience/arteries.png",
    time: "Apr 2022 - Aug 2022",
    location: "Budapest, Hungary",
    footer: "",
    description: "Cross-platform mobile development in Flutter (Dart, BLoC) using GitHub as part of a multidisciplinary agile team. Implemented screens, widgets, push notifications (Firebase), Google and Apple social logins. Used REST to communicate with a server and public APIs.",
  }
];